name: deploy via rsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: "wp-content/"
          TARGET: "/code/wp-content/"
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "latest"
          cache: "npm"
      - name: Node - install dependencies
        run: npm install
      - name: Node - start localhost:8881 proxy
        run: npx http-server -P https://dev-sg-capstone.pantheonsite.io -p 8881 &
      - name: Node - start localhost:8882 proxy
        run: npx http-server -P https://dev-sg-capstone.pantheonsite.io -p 8882 &
      - name: Cypress run
        uses: cypress-io/github-action@v6