name: deploy via rsync

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Checkout database
        uses: actions/checkout@v4
        with:
          ref: main
          repository: Sound-Generations-Capstone/database
          path: ./wp-content/database
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to Test Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.TEST_HOST }}
          REMOTE_USER: ${{ secrets.TEST_USER }}
          REMOTE_PORT: ${{ secrets.TEST_PORT }}
          SOURCE: "wp-content/"
          TARGET: "/code/wp-content/"
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 'latest'
          cache: 'npm'
      - name: Node - install dependencies
        run: npm install
      - name: Node - start http proxy
        run: npx http-server -P https://dev-test-sg-capstone.pantheonsite.io -p 8881 &
      - name: Cypress run
        uses: cypress-io/github-action@v6

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
          SOURCE: "wp-content/"
          TARGET: "/code/wp-content/"
